export interface Track {
  id: string
  title: string
  artist: string
  duration: string
  audioUrl: string
  downloadUrl: string
}

export const dancehallSquareTracks: Track[] = [
  {
    id: "dancehall-1",
    title: "Baby Come Back Home",
    artist: "AI Selector",
    duration: "3:22",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/baby-come-back-home-Yr7uMChWHv0uhvCxSlHW2QIclNSGNc.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/baby-come-back-home-Yr7uMChWHv0uhvCxSlHW2QIclNSGNc.mp3",
  },
  {
    id: "dancehall-2",
    title: "Baby Yuh Perfect",
    artist: "Digital Yardie",
    duration: "3:35",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/baby-yuh-perfect-GzmqgYAvlWLOqFSotTvDMr5Vh4UPtn.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/baby-yuh-perfect-GzmqgYAvlWLOqFSotTvDMr5Vh4UPtn.mp3",
  },
  {
    id: "dancehall-3",
    title: "Bubble and Wine",
    artist: "Cyber Dancehall",
    duration: "3:18",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bubble-and-wine-NcLdMBMD7Z1OkbQJ9UwQqP6VmPYAzH.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bubble-and-wine-NcLdMBMD7Z1OkbQJ9UwQqP6VmPYAzH.mp3",
  },
  {
    id: "dancehall-4",
    title: "Driver's Seat",
    artist: "Virtual Deejay",
    duration: "3:41",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/driver%27s-seat-xyDyS9ejtmQhsvbHqI9ABxnlsJ1hUC.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/driver%27s-seat-xyDyS9ejtmQhsvbHqI9ABxnlsJ1hUC.mp3",
  },
  {
    id: "dancehall-5",
    title: "Empress Rise Up",
    artist: "AI Soundsystem",
    duration: "3:29",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/empress-rise-up-Cg5ahup01tQQStwg5iRLXZbkMKT1Dd.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/empress-rise-up-Cg5ahup01tQQStwg5iRLXZbkMKT1Dd.mp3",
  },
  {
    id: "dancehall-6",
    title: "Bad Gyal Anthem",
    artist: "Digital Queen",
    duration: "3:14",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bad-gyal-anthem-dvUrOdaWRGqyGHqQKW4MQaBoTiuJsK.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bad-gyal-anthem-dvUrOdaWRGqyGHqQKW4MQaBoTiuJsK.mp3",
  },
  {
    id: "dancehall-7",
    title: "Bubble fi Di Real Don",
    artist: "Cyber Selector",
    duration: "3:38",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bubble-fi-di-real-don-lwuNmhvLJhGINx0D2FJmDPGV1AI0te.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bubble-fi-di-real-don-lwuNmhvLJhGINx0D2FJmDPGV1AI0te.mp3",
  },
  {
    id: "dancehall-8",
    title: "Carnival Queen",
    artist: "AI Bashment",
    duration: "3:25",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/carnival-queen-UpYFrEfHpkJkcoArbQyIQK549i3aUl.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/carnival-queen-UpYFrEfHpkJkcoArbQyIQK549i3aUl.mp3",
  },
  {
    id: "dancehall-9",
    title: "Black Queen Anthem",
    artist: "Virtual Empress",
    duration: "3:31",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/black-queen-anthem-NDwFeR3OpLUXma9h5eBUeMUF0kVF5N.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/black-queen-anthem-NDwFeR3OpLUXma9h5eBUeMUF0kVF5N.mp3",
  },
  {
    id: "dancehall-10",
    title: "Baby Yuh So Fine",
    artist: "Digital Lover",
    duration: "3:16",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/baby-yuh-so-fine-0DuDJNL1OP1eLpfsGrUlaZJiTmgRjD.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/baby-yuh-so-fine-0DuDJNL1OP1eLpfsGrUlaZJiTmgRjD.mp3",
  },
  {
    id: "dancehall-11",
    title: "Gyal Power",
    artist: "Empress Digital",
    duration: "3:27",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-power-sSXbTFG1R5cBGPZeU5ByreN3IHmH9B.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-power-sSXbTFG1R5cBGPZeU5ByreN3IHmH9B.mp3",
  },
  {
    id: "dancehall-12",
    title: "Gyalis But Yuh Win",
    artist: "Heartbreak Selector",
    duration: "3:33",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyalis-but-yuh-win-IRhr6Jow9P2E4piHysMC2u8p4j8Cez.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyalis-but-yuh-win-IRhr6Jow9P2E4piHysMC2u8p4j8Cez.mp3",
  },
  {
    id: "dancehall-13",
    title: "Island Gyal",
    artist: "Caribbean AI",
    duration: "3:19",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/island-gyal-Ptsf6QX0dmr7WQxAzK4RJubtvZNKoN.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/island-gyal-Ptsf6QX0dmr7WQxAzK4RJubtvZNKoN.mp3",
  },
  {
    id: "dancehall-14",
    title: "Ganja Farmer's Anthem",
    artist: "Rasta Digital",
    duration: "3:45",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ganja-farmer%27s-anthem-qFT9VUQ1PNKKUaOHpEzSlRsBhzPqdU.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ganja-farmer%27s-anthem-qFT9VUQ1PNKKUaOHpEzSlRsBhzPqdU.mp3",
  },
  {
    id: "dancehall-15",
    title: "Gyal Yuh Have Mi Crazy",
    artist: "Love Struck AI",
    duration: "3:31",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-have-mi-crazy-YClQpuY49BIz9HkP9eIjuONbVXOdbR.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-have-mi-crazy-YClQpuY49BIz9HkP9eIjuONbVXOdbR.mp3",
  },
  {
    id: "dancehall-16",
    title: "Gyal Yuh Bad Sample",
    artist: "Bad Gyal Producer",
    duration: "3:24",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-bad-sample-RQKqjMz7dO1CzKhkMF6uCfxGD61quO.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-bad-sample-RQKqjMz7dO1CzKhkMF6uCfxGD61quO.mp3",
  },
  {
    id: "dancehall-17",
    title: "Gyal Yuh Body Hot",
    artist: "Fire Selector",
    duration: "3:36",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-body-hot-En6rvlo1jeo5ALsrL43oREP6Rj2xOF.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-body-hot-En6rvlo1jeo5ALsrL43oREP6Rj2xOF.mp3",
  },
  {
    id: "dancehall-18",
    title: "Graduation Love",
    artist: "Young Love AI",
    duration: "3:28",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/graduation-love-VYgbYx9MNJmlAvXGOu2FWJQRvW4bPi.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/graduation-love-VYgbYx9MNJmlAvXGOu2FWJQRvW4bPi.mp3",
  },
  {
    id: "dancehall-19",
    title: "Give Mi Yuh Heart",
    artist: "Romance Riddim",
    duration: "3:42",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/give-mi-yuh-heart-oUwzKONywouwm0oghxeplbahcvQVvb.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/give-mi-yuh-heart-oUwzKONywouwm0oghxeplbahcvQVvb.mp3",
  },
  {
    id: "dancehall-20",
    title: "Gyal Yuh Sweet So",
    artist: "Sweet Vibes AI",
    duration: "3:29",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-sweet-so-kEruwswBMgcOczyVCKnjkgg94g5Ngf.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gyal-yuh-sweet-so-kEruwswBMgcOczyVCKnjkgg94g5Ngf.mp3",
  },
  {
    id: "dancehall-21",
    title: "Mi Cyaa Sleep Widout Yuh Snore",
    artist: "Bedroom Riddim AI",
    duration: "3:34",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-cyaa-sleep-widout-yuh-snore-ETcSfFzP0WA2qW1zNbTBL8ZHhl0M9p.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-cyaa-sleep-widout-yuh-snore-ETcSfFzP0WA2qW1zNbTBL8ZHhl0M9p.mp3",
  },
  {
    id: "dancehall-22",
    title: "Market Day",
    artist: "Street Life Digital",
    duration: "3:26",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/market-day-vhRBrjMB8LY8X2jf2Nis31eDzKdRD8.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/market-day-vhRBrjMB8LY8X2jf2Nis31eDzKdRD8.mp3",
  },
  {
    id: "dancehall-23",
    title: "Mi Adore Yuh",
    artist: "Pure Love AI",
    duration: "3:39",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-adore-yuh-SLiruUueaMbMyUVslWq5SKOgcyjDhi.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-adore-yuh-SLiruUueaMbMyUVslWq5SKOgcyjDhi.mp3",
  },
  {
    id: "dancehall-24",
    title: "Kitchen Serenade",
    artist: "Home Sweet Home AI",
    duration: "3:32",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kitchen-serenade-itg9oBg6C92Q7dt21WzXZgpnMyMiyC.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kitchen-serenade-itg9oBg6C92Q7dt21WzXZgpnMyMiyC.mp3",
  },
  {
    id: "dancehall-25",
    title: "Mi Heart Have Yuh GPS",
    artist: "Modern Love Digital",
    duration: "3:28",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-have-yuh-gps-6d2cKNwQd906RqQ5nwaebrFZksDqIr.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-have-yuh-gps-6d2cKNwQd906RqQ5nwaebrFZksDqIr.mp3",
  },
  {
    id: "dancehall-26",
    title: "Mi Heart Deh Pan You",
    artist: "Heartstring AI",
    duration: "3:41",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-deh-pan-you-d15SAg147le5RKNFEqNkIfl6tyvQMg.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-deh-pan-you-d15SAg147le5RKNFEqNkIfl6tyvQMg.mp3",
  },
  {
    id: "dancehall-27",
    title: "Mi Heart Deh Pan You (Remix)",
    artist: "Heartstring AI ft. Digital Selector",
    duration: "3:47",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-deh-pan-you-remix-Zaqrisy0H3vrBAPVTf63TRCwk6vPBC.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-deh-pan-you-remix-Zaqrisy0H3vrBAPVTf63TRCwk6vPBC.mp3",
  },
  {
    id: "dancehall-28",
    title: "Mi Heart Beat Fi You",
    artist: "Pulse Riddim AI",
    duration: "3:35",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-beat-fi-you-jOkMiJoX5c86WgZgawQTFcFpmThHUE.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-heart-beat-fi-you-jOkMiJoX5c86WgZgawQTFcFpmThHUE.mp3",
  },
  {
    id: "dancehall-29",
    title: "Love Mi Like Sunday Morning",
    artist: "Sunday Vibes Digital",
    duration: "3:43",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/love-mi-like-sunday-morning-fxXHrDPbZcVQxpYhJxPlPgbOchEjFT.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/love-mi-like-sunday-morning-fxXHrDPbZcVQxpYhJxPlPgbOchEjFT.mp3",
  },
  {
    id: "dancehall-30",
    title: "Jealous Gyal",
    artist: "Green Eye AI",
    duration: "3:30",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/jealous-gyal-wdalswVXMMyb1InIaZM08Hz4X5N0Oo.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/jealous-gyal-wdalswVXMMyb1InIaZM08Hz4X5N0Oo.mp3",
  },
  {
    id: "dancehall-31",
    title: "Mi Waan Fi Hold Yuh",
    artist: "Tender Touch AI",
    duration: "3:37",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-waan-fi-hold-yuh-6iLf1togs2lHRR1oQBXYc1i0CBCam7.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-waan-fi-hold-yuh-6iLf1togs2lHRR1oQBXYc1i0CBCam7.mp3",
  },
  {
    id: "dancehall-32",
    title: "Mi Love Yuh Like Cook Food (Remix)",
    artist: "Kitchen Love AI ft. Spice Digital",
    duration: "3:44",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-love-yuh-like-cook-food-remix-HWyVB7hic3O3DlGBcSsgvHxV3dtnrs.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-love-yuh-like-cook-food-remix-HWyVB7hic3O3DlGBcSsgvHxV3dtnrs.mp3",
  },
  {
    id: "dancehall-33",
    title: "Mi Nuh Want Nobody Else",
    artist: "Loyal Heart AI",
    duration: "3:33",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-nuh-want-nobody-else-HfqHyRhcnYrKF4gLx4gH18Vv2q4zzS.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-nuh-want-nobody-else-HfqHyRhcnYrKF4gLx4gH18Vv2q4zzS.mp3",
  },
  {
    id: "dancehall-34",
    title: "Mi Nuh Trust Dem, But Yuh",
    artist: "Trust Issues Digital",
    duration: "3:40",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-nuh-trust-dem%2C-but-yuh-RzKGHtGNNoyN4X5OKZ5rHdoSc7Es2s.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-nuh-trust-dem%2C-but-yuh-RzKGHtGNNoyN4X5OKZ5rHdoSc7Es2s.mp3",
  },
  {
    id: "dancehall-35",
    title: "Mi Nah Share Yuh",
    artist: "Possessive Love AI",
    duration: "3:29",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-nah-share-yuh-9RaJSClnr5txcgwcJuSqfHr3k9hocb.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-nah-share-yuh-9RaJSClnr5txcgwcJuSqfHr3k9hocb.mp3",
  },
  {
    id: "dancehall-36",
    title: "Mi Phone Fulla Yuh",
    artist: "Digital Age Romance",
    duration: "3:31",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-phone-fulla-yuh-SX28xFflB1y61HGRSbIqGBowwDw7VQ.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-phone-fulla-yuh-SX28xFflB1y61HGRSbIqGBowwDw7VQ.mp3",
  },
  {
    id: "dancehall-37",
    title: "Mi Love Yuh Like Cook Food",
    artist: "Kitchen Love AI",
    duration: "3:38",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-love-yuh-like-cook-food-4Ari2fP73GxK62Sd1VgfgqmtHpbXix.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-love-yuh-like-cook-food-4Ari2fP73GxK62Sd1VgfgqmtHpbXix.mp3",
  },
  {
    id: "dancehall-38",
    title: "Mi Wife But She Nuh Know",
    artist: "Secret Husband AI",
    duration: "3:42",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-wife-but-she-nuh-know-bPmPUMiqh5sz5akiZep6IjO1e7YuJy.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-wife-but-she-nuh-know-bPmPUMiqh5sz5akiZep6IjO1e7YuJy.mp3",
  },
  {
    id: "dancehall-39",
    title: "Midnight Confession",
    artist: "Late Night Truth AI",
    duration: "3:35",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/midnight-confession-P9JXw99LJBrRGBFeXWdYsyyDlC8HEE.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/midnight-confession-P9JXw99LJBrRGBFeXWdYsyyDlC8HEE.mp3",
  },
  {
    id: "dancehall-40",
    title: "Mi Love Yuh More",
    artist: "Endless Love Digital",
    duration: "3:46",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-love-yuh-more-YY0RcHc8dQvUtbe5ftl8nzH9y6ocP0.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mi-love-yuh-more-YY0RcHc8dQvUtbe5ftl8nzH9y6ocP0.mp3",
  },
  {
    id: "dancehall-41",
    title: "Tek Back Mi Chain But Nuh Tek Back Mi Love",
    artist: "Heartbreak Warrior AI",
    duration: "3:52",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tek-back-mi-chain-but-nuh-tek-back-mi-love-8TvCZmMgXVFAeuYkE4mfqkRpxOcJeg.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tek-back-mi-chain-but-nuh-tek-back-mi-love-8TvCZmMgXVFAeuYkE4mfqkRpxOcJeg.mp3",
  },
  {
    id: "dancehall-42",
    title: "Rude Boy Loving",
    artist: "Bad Boy Romance AI",
    duration: "3:33",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rude-boy-loving-1npbvSmsLnZeYbpgZob8SSeuii0DUn.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rude-boy-loving-1npbvSmsLnZeYbpgZob8SSeuii0DUn.mp3",
  },
  {
    id: "dancehall-43",
    title: "Nuh Text Mi Ex",
    artist: "Boundary Setting Digital",
    duration: "3:27",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nuh-text-mi-ex-qaWhC0RZoQh878J9wslpPz3lRvDMOi.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nuh-text-mi-ex-qaWhC0RZoQh878J9wslpPz3lRvDMOi.mp3",
  },
  {
    id: "dancehall-44",
    title: "Sistah Unity",
    artist: "Women Power AI",
    duration: "3:41",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/sistah-unity-mpyft268SqnoIPYAZEyFKNBQtV94hx.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/sistah-unity-mpyft268SqnoIPYAZEyFKNBQtV94hx.mp3",
  },
  {
    id: "dancehall-45",
    title: "Rainy Day Love",
    artist: "Weather Mood Digital",
    duration: "3:38",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rainy-day-love-gpm7HXtBygM6xDg2mgZt1Rf6tNY6TT.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rainy-day-love-gpm7HXtBygM6xDg2mgZt1Rf6tNY6TT.mp3",
  },
  {
    id: "dancehall-46",
    title: "Tek Mi Home",
    artist: "Journey's End AI",
    duration: "3:34",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tek-mi-home-LqANerZ0CoIYnTVrwyPwjpZMrDH0bK.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tek-mi-home-LqANerZ0CoIYnTVrwyPwjpZMrDH0bK.mp3",
  },
  {
    id: "dancehall-47",
    title: "Ride Wid Mi",
    artist: "Adventure Love Digital",
    duration: "3:29",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ride-wid-mi-NEBN4wFQfyJdKzmGPSBn1YH8A0VNcn.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ride-wid-mi-NEBN4wFQfyJdKzmGPSBn1YH8A0VNcn.mp3",
  },
  {
    id: "dancehall-48",
    title: "Nuh Badda Try Hold Mi Down",
    artist: "Freedom Fighter AI",
    duration: "3:45",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nuh-badda-try-hold-mi-down-5ZZGPW7otVFqI6yzQzDLZRmMZNkUM0.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nuh-badda-try-hold-mi-down-5ZZGPW7otVFqI6yzQzDLZRmMZNkUM0.mp3",
  },
  {
    id: "dancehall-49",
    title: "Skin Like Milo Tea",
    artist: "Sweet Complexion Digital",
    duration: "3:31",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/skin-like-milo-tea-RECzGmIaDgP1aGoQanOKoBYs3Fq25W.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/skin-like-milo-tea-RECzGmIaDgP1aGoQanOKoBYs3Fq25W.mp3",
  },
  {
    id: "dancehall-50",
    title: "She Say Mi Toxic",
    artist: "Relationship Drama AI",
    duration: "3:39",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/she-say-mi-toxic-3QyufDYBizFyzqtgHuTau2WhOMSMOO.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/she-say-mi-toxic-3QyufDYBizFyzqtgHuTau2WhOMSMOO.mp3",
  },
  {
    id: "dancehall-51",
    title: "Yuh A Mi Blessing",
    artist: "Grateful Heart AI",
    duration: "3:43",
    audioUrl: "/audio/dancehall-square/yuh-a-mi-blessing.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-a-mi-blessing.mp3",
  },
  {
    id: "dancehall-52",
    title: "Wine Fi Mi Baby",
    artist: "Dance Floor Romance",
    duration: "3:36",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/wine-fi-mi-baby-ZdyS5Liio9v53iGLwcY6mVXlz9CCtk.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/wine-fi-mi-baby-ZdyS5Liio9v53iGLwcY6mVXlz9CCtk.mp3",
  },
  {
    id: "dancehall-53",
    title: "Yuh Make Mi Crazy Inna Love",
    artist: "Mad Love Digital",
    duration: "3:41",
    audioUrl: "/audio/dancehall-square/yuh-make-mi-crazy-inna-love.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-make-mi-crazy-inna-love.mp3",
  },
  {
    id: "dancehall-54",
    title: "Yuh Body Talk To Mi",
    artist: "Silent Communication AI",
    duration: "3:34",
    audioUrl: "/audio/dancehall-square/yuh-body-talk-to-mi.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-body-talk-to-mi.mp3",
  },
  {
    id: "dancehall-55",
    title: "Wine Slow Pon Mi Ego",
    artist: "Humble Vibes Digital",
    duration: "3:38",
    audioUrl: "/audio/dancehall-square/wine-slow-pon-mi-ego.mp3",
    downloadUrl: "/audio/dancehall-square/wine-slow-pon-mi-ego.mp3",
  },
  {
    id: "dancehall-56",
    title: "Wi Stronger Than Dem Think",
    artist: "Unity Power AI",
    duration: "3:47",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/wi-stronger-than-dem-think-tF7822cb1jxZiaWhOoxuuMkKSMuM9Y.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/wi-stronger-than-dem-think-tF7822cb1jxZiaWhOoxuuMkKSMuM9Y.mp3",
  },
  {
    id: "dancehall-57",
    title: "Yuh Love Strong",
    artist: "Solid Foundation Digital",
    duration: "3:32",
    audioUrl: "/audio/dancehall-square/yuh-love-strong.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-love-strong.mp3",
  },
  {
    id: "dancehall-58",
    title: "Visa Run",
    artist: "Immigration Blues AI",
    duration: "3:29",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/visa-run-MpezfarnENeTTklcBHYS6KJhlAtKP8.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/visa-run-MpezfarnENeTTklcBHYS6KJhlAtKP8.mp3",
  },
  {
    id: "dancehall-59",
    title: "Whatsapp Love II",
    artist: "Digital Romance AI",
    duration: "3:45",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/whatsapp-love-ii-8Eh9dLoAWQKuDVAXlQFl3mn0gBbWd9.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/whatsapp-love-ii-8Eh9dLoAWQKuDVAXlQFl3mn0gBbWd9.mp3",
  },
  {
    id: "dancehall-60",
    title: "WhatsApp Love",
    artist: "Digital Romance AI",
    duration: "3:40",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/whatsapp-love-NIFO8gIA1HFNQoN2MBLywa01eeubW9.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/whatsapp-love-NIFO8gIA1HFNQoN2MBLywa01eeubW9.mp3",
  },
  {
    id: "dancehall-61",
    title: "Yuh Tek All Di Sheet II",
    artist: "Bedroom Bandit AI",
    duration: "3:44",
    audioUrl: "/audio/dancehall-square/yuh-tek-all-di-sheet-ii.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-tek-all-di-sheet-ii.mp3",
  },
  {
    id: "dancehall-62",
    title: "Yuh Mek Mi Feel Like King",
    artist: "Royal Treatment Digital",
    duration: "3:37",
    audioUrl: "/audio/dancehall-square/yuh-mek-mi-feel-like-king.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-mek-mi-feel-like-king.mp3",
  },
  {
    id: "dancehall-63",
    title: "Yuh Smile Tek Mi Credit",
    artist: "Broke But Happy AI",
    duration: "3:33",
    audioUrl: "/audio/dancehall-square/yuh-smile-tek-mi-credit.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-smile-tek-mi-credit.mp3",
  },
  {
    id: "dancehall-64",
    title: "Yuh Tek All Di Sheet",
    artist: "Bedroom Bandit AI",
    duration: "3:41",
    audioUrl: "/audio/dancehall-square/yuh-tek-all-di-sheet.mp3",
    downloadUrl: "/audio/dancehall-square/yuh-tek-all-di-sheet.mp3",
  },
  {
    id: "dancehall-65",
    title: "Closer",
    artist: "AI Selector",
    duration: "3:28",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/closer-oxommeksZZrheaAkPArB8Sdnb7Tx7p.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/closer-oxommeksZZrheaAkPArB8Sdnb7Tx7p.mp3",
  },
  {
    id: "dancehall-66",
    title: "Do You See Mi Slo",
    artist: "Digital Yardie",
    duration: "3:35",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/do-you-see-mi-slo-rNL3eZYvfqv8kd6lq4kQlO3uDM0KGJ.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/do-you-see-mi-slo-rNL3eZYvfqv8kd6lq4kQlO3uDM0KGJ.mp3",
  },
  {
    id: "dancehall-67",
    title: "Do You See Mi",
    artist: "Digital Yardie",
    duration: "3:30",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/do-you-see-mi-7I2z5TdW7roK1VC7j9GCGnOea9zCPp.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/do-you-see-mi-7I2z5TdW7roK1VC7j9GCGnOea9zCPp.mp3",
  },
  {
    id: "dancehall-68",
    title: "He Tek It",
    artist: "Bashment Queen",
    duration: "3:25",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/he-tek-it-Rg2x6ZpChUbM0qNnqI6AsBOxPffrgu.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/he-tek-it-Rg2x6ZpChUbM0qNnqI6AsBOxPffrgu.mp3",
  },
  {
    id: "dancehall-69",
    title: "Steady Rising",
    artist: "Roots Rebel AI",
    duration: "3:32",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/steady-rising-4Mjb1FelZ51DgRJrr3mkLub9NSI4yK.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/steady-rising-4Mjb1FelZ51DgRJrr3mkLub9NSI4yK.mp3",
  },
]
