export interface RnBSquareTrack {
  id: number
  title: string
  artist: string
  duration: string
  audioUrl: string
  downloadUrl: string
  coverArt?: string
}

export const rnbSquareTracks: RnBSquareTrack[] = [
  {
    id: 1,
    title: "Can't Hide",
    artist: "R&B Square Artist",
    duration: "3:42",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Can't%20Hide-RnBSquare1.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Can't%20Hide-RnBSquare1.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 2,
    title: "Breakfast In Bed",
    artist: "R&B Square Artist",
    duration: "4:15",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Breakfast%20In%20Bed-RnBSquare2.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Breakfast%20In%20Bed-RnBSquare2.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 3,
    title: "A Night To Remember",
    artist: "R&B Square Artist",
    duration: "3:58",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/A%20Night%20To%20Remember-RnBSquare3.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/A%20Night%20To%20Remember-RnBSquare3.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 4,
    title: "Around You",
    artist: "R&B Square Artist",
    duration: "4:03",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Around%20You-RnBSquare4.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Around%20You-RnBSquare4.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 5,
    title: "Care For You",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Care%20For%20You-RnBSquare5.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Care%20For%20You-RnBSquare5.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 6,
    title: "Beautiful Things",
    artist: "R&B Square Artist",
    duration: "4:21",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Beautiful%20Things-RnBSquare6.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Beautiful%20Things-RnBSquare6.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 7,
    title: "Care For You II",
    artist: "R&B Square Artist",
    duration: "3:54",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Care%20For%20You%20II-RnBSquare7.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Care%20For%20You%20II-RnBSquare7.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 8,
    title: "Believer",
    artist: "R&B Square Artist",
    duration: "4:08",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Believer-RnBSquare8.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Believer-RnBSquare8.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 9,
    title: "Broken Things",
    artist: "R&B Square Artist",
    duration: "3:36",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Broken%20Things-RnBSquare9.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Broken%20Things-RnBSquare9.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 10,
    title: "Bedtime Stories",
    artist: "R&B Square Artist",
    duration: "4:12",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bedtime%20Stories-RnBSquare10.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bedtime%20Stories-RnBSquare10.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 11,
    title: "Chills On My Body",
    artist: "R&B Square Artist",
    duration: "4:15",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chills%20On%20My%20Body-RnBSquare11.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chills%20On%20My%20Body-RnBSquare11.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 12,
    title: "Dancing In The Dark",
    artist: "R&B Square Artist",
    duration: "3:54",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Dancing%20In%20The%20Dark-RnBSquare12.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Dancing%20In%20The%20Dark-RnBSquare12.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 13,
    title: "Do It For Me",
    artist: "R&B Square Artist",
    duration: "3:42",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Do%20It%20For%20Me-RnBSquare13.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Do%20It%20For%20Me-RnBSquare13.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 14,
    title: "Good Game",
    artist: "R&B Square Artist",
    duration: "3:36",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Good%20Game-RnBSquare14.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Good%20Game-RnBSquare14.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 15,
    title: "Fire On My Heart",
    artist: "R&B Square Artist",
    duration: "4:12",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fire%20On%20My%20Heart-RnBSquare15.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fire%20On%20My%20Heart-RnBSquare15.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 16,
    title: "Hot & Rainy II",
    artist: "R&B Square Artist",
    duration: "4:08",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Hot%20&%20Rainy%20II-RnBSquare16.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Hot%20&%20Rainy%20II-RnBSquare16.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 17,
    title: "Care For You (New Version)",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Care%20For%20You%20(New%20Version)-RnBSquare17.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Care%20For%20You%20(New%20Version)-RnBSquare17.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 18,
    title: "Grown & Fine",
    artist: "R&B Square Artist",
    duration: "4:21",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Grown%20&%20Fine-RnBSquare18.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Grown%20&%20Fine-RnBSquare18.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 19,
    title: "Hard To Love",
    artist: "R&B Square Artist",
    duration: "3:58",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Hard%20To%20Love-RnBSquare19.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Hard%20To%20Love-RnBSquare19.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 20,
    title: "Here For It",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Here%20For%20It-RnBSquare20.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Here%20For%20It-RnBSquare20.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 21,
    title: "Love You Like I Do",
    artist: "R&B Square Artist",
    duration: "4:05",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Love%20You%20Like%20I%20Do-RnBSquare21.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Love%20You%20Like%20I%20Do-RnBSquare21.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 22,
    title: "Love You Like I Do (Unplugged)",
    artist: "R&B Square Artist",
    duration: "3:52",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Love%20You%20Like%20I%20Do%20(Unplugged)-RnBSquare22.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Love%20You%20Like%20I%20Do%20(Unplugged)-RnBSquare22.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 23,
    title: "Mess Up The Bed",
    artist: "R&B Square Artist",
    duration: "4:18",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mess%20Up%20The%20Bed-RnBSquare23.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Mess%20Up%20The%20Bed-RnBSquare23.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 24,
    title: "Night To Remember",
    artist: "R&B Square Artist",
    duration: "3:44",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Night%20To%20Remember-RnBSquare24.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Night%20To%20Remember-RnBSquare24.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 25,
    title: "Let's Make It A Night",
    artist: "R&B Square Artist",
    duration: "4:09",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Let's%20Make%20It%20A%20Night-RnBSquare25.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Let's%20Make%20It%20A%20Night-RnBSquare25.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 26,
    title: "Point Of It All",
    artist: "R&B Square Artist",
    duration: "3:56",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Point%20Of%20It%20All-RnBSquare26.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Point%20Of%20It%20All-RnBSquare26.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 27,
    title: "I Never Stood A Chance",
    artist: "R&B Square Artist",
    duration: "4:14",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/I%20Never%20Stood%20A%20Chance-RnBSquare27.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/I%20Never%20Stood%20A%20Chance-RnBSquare27.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 28,
    title: "Out Of My Dreams",
    artist: "R&B Square Artist",
    duration: "3:48",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Out%20Of%20My%20Dreams-RnBSquare28.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Out%20Of%20My%20Dreams-RnBSquare28.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 29,
    title: "Hot & Rainy",
    artist: "R&B Square Artist",
    duration: "4:02",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Hot%20&%20Rainy-RnBSquare29.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Hot%20&%20Rainy-RnBSquare29.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 30,
    title: "Letting It Fall II",
    artist: "R&B Square Artist",
    duration: "3:59",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Letting%20It%20Fall%20II-RnBSquare30.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Letting%20It%20Fall%20II-RnBSquare30.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 31,
    title: "The One",
    artist: "R&B Square Artist",
    duration: "4:07",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/The%20One-RnBSquare31.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/The%20One-RnBSquare31.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 32,
    title: "The Little Things II",
    artist: "R&B Square Artist",
    duration: "3:51",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/The%20Little%20Things%20II-RnBSquare32.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/The%20Little%20Things%20II-RnBSquare32.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 33,
    title: "The Little Things",
    artist: "R&B Square Artist",
    duration: "4:03",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/The%20Little%20Things-RnBSquare33.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/The%20Little%20Things-RnBSquare33.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 34,
    title: "Safe Space",
    artist: "R&B Square Artist",
    duration: "3:45",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Safe%20Space-RnBSquare34.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Safe%20Space-RnBSquare34.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 35,
    title: "Secret Lover",
    artist: "R&B Square Artist",
    duration: "4:16",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Secret%20Lover-RnBSquare35.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Secret%20Lover-RnBSquare35.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 36,
    title: "Time Well Spent",
    artist: "R&B Square Artist",
    duration: "3:58",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Time%20Well%20Spent-RnBSquare36.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Time%20Well%20Spent-RnBSquare36.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 37,
    title: "She's A Vibe",
    artist: "R&B Square Artist",
    duration: "4:11",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/She's%20A%20Vibe-RnBSquare37.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/She's%20A%20Vibe-RnBSquare37.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 38,
    title: "Tears In The Sun",
    artist: "R&B Square Artist",
    duration: "3:49",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tears%20In%20The%20Sun-RnBSquare38.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tears%20In%20The%20Sun-RnBSquare38.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 39,
    title: "Ready To Jump",
    artist: "R&B Square Artist",
    duration: "4:04",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ready%20To%20Jump-RnBSquare39.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ready%20To%20Jump-RnBSquare39.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 40,
    title: "Room In Your Heart",
    artist: "R&B Square Artist",
    duration: "3:56",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Room%20In%20Your%20Heart-RnBSquare40.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Room%20In%20Your%20Heart-RnBSquare40.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 41,
    title: "Tons",
    artist: "R&B Square Artist",
    duration: "4:13",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tons-RnBSquare41.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tons-RnBSquare41.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 42,
    title: "Wrapped",
    artist: "R&B Square Artist",
    duration: "3:47",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wrapped-RnBSquare42.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wrapped-RnBSquare42.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 43,
    title: "Wheels Fall Off",
    artist: "R&B Square Artist",
    duration: "4:05",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wheels%20Fall%20Off-RnBSquare43.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wheels%20Fall%20Off-RnBSquare43.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 44,
    title: "You Have Found Me II",
    artist: "R&B Square Artist",
    duration: "3:52",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/You%20Have%20Found%20Me%20II-RnBSquare44.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/You%20Have%20Found%20Me%20II-RnBSquare44.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 45,
    title: "You Know Better",
    artist: "R&B Square Artist",
    duration: "4:08",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/You%20Know%20Better-RnBSquare45.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/You%20Know%20Better-RnBSquare45.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 46,
    title: "Walls Down",
    artist: "R&B Square Artist",
    duration: "3:59",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Walls%20Down-RnBSquare46.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Walls%20Down-RnBSquare46.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 47,
    title: "You Have Found Me",
    artist: "R&B Square Artist",
    duration: "4:01",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/You%20Have%20Found%20Me-RnBSquare47.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/You%20Have%20Found%20Me-RnBSquare47.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 48,
    title: "Weak",
    artist: "R&B Square Artist",
    duration: "3:43",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Weak-RnBSquare48.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Weak-RnBSquare48.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 49,
    title: "Worth It Anyway",
    artist: "R&B Square Artist",
    duration: "4:17",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Worth%20It%20Anyway-RnBSquare49.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Worth%20It%20Anyway-RnBSquare49.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 50,
    title: "Turn Around",
    artist: "R&B Square Artist",
    duration: "3:54",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Turn%20Around-RnBSquare50.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Turn%20Around-RnBSquare50.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 51,
    title: "Golden Hour Confessions",
    artist: "Luv Tonez",
    duration: "3:48",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Golden%20Hour%20Confessions-RnBSquare51.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Golden%20Hour%20Confessions-RnBSquare51.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 52,
    title: "Electric Souls II",
    artist: "Luv Tonez",
    duration: "4:02",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Electric%20Souls%20II-RnBSquare52.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Electric%20Souls%20II-RnBSquare52.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 53,
    title: "Electric Souls",
    artist: "Luv Tonez",
    duration: "3:55",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Electric%20Souls-RnBSquare53.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Electric%20Souls-RnBSquare53.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 54,
    title: "3AM Conversations",
    artist: "Luv Tonez",
    duration: "4:18",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/3AM%20Conversations-RnBSquare54.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/3AM%20Conversations-RnBSquare54.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 55,
    title: "City Lights & Late Nights",
    artist: "Luv Tonez",
    duration: "3:42",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/City%20Lights%20&%20Late%20Nights-RnBSquare55.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/City%20Lights%20&%20Late%20Nights-RnBSquare55.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 56,
    title: "Digital Love Letters",
    artist: "Luv Tonez",
    duration: "4:05",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Digital%20Love%20Letters-RnBSquare56.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Digital%20Love%20Letters-RnBSquare56.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 57,
    title: "Bamboo Sheets",
    artist: "Luv Tonez",
    duration: "3:38",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bamboo%20Sheets-RnBSquare57.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bamboo%20Sheets-RnBSquare57.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 58,
    title: "Kaleidoscope Hearts (Remix)",
    artist: "Luv Tonez",
    duration: "4:12",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kaleidoscope%20Hearts%20(Remix)-RnBSquare58.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kaleidoscope%20Hearts%20(Remix)-RnBSquare58.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 59,
    title: "Gravity",
    artist: "Luv Tonez",
    duration: "3:51",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Gravity-RnBSquare59.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Gravity-RnBSquare59.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 60,
    title: "Honey Drip",
    artist: "Luv Tonez",
    duration: "4:08",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Honey%20Drip-RnBSquare60.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Honey%20Drip-RnBSquare60.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 61,
    title: "Neon Heartbreak",
    artist: "Luv Tonez",
    duration: "3:54",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Neon%20Heartbreak-RnBSquare61.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Neon%20Heartbreak-RnBSquare61.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 62,
    title: "Rose Gold Feelings",
    artist: "Luv Tonez",
    duration: "4:16",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Rose%20Gold%20Feelings-RnBSquare62.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Rose%20Gold%20Feelings-RnBSquare62.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 63,
    title: "Kaleidoscope Hearts",
    artist: "Luv Tonez",
    duration: "3:47",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kaleidoscope%20Hearts-RnBSquare63.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kaleidoscope%20Hearts-RnBSquare63.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 64,
    title: "Kaleidoscope Hearts (Dance Mix)",
    artist: "Luv Tonez",
    duration: "4:23",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kaleidoscope%20Hearts%20(Dance%20Mix)-RnBSquare64.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kaleidoscope%20Hearts%20(Dance%20Mix)-RnBSquare64.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 65,
    title: "Silk Road",
    artist: "Luv Tonez",
    duration: "4:01",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Silk%20Road-RnBSquare65.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Silk%20Road-RnBSquare65.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 66,
    title: "Stardust Serenade (Extended)",
    artist: "Luv Tonez",
    duration: "5:12",
    audioUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Stardust%20Serenade%20(Extended)-RnBSquare66.mp3",
    downloadUrl:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Stardust%20Serenade%20(Extended)-RnBSquare66.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 67,
    title: "Purple Rain Therapy",
    artist: "Luv Tonez",
    duration: "4:35",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Purple%20Rain%20Therapy-RnBSquare67.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Purple%20Rain%20Therapy-RnBSquare67.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 68,
    title: "Midnight Frequencie",
    artist: "Luv Tonez",
    duration: "3:58",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Midnight%20Frequencie-RnBSquare68.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Midnight%20Frequencie-RnBSquare68.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 69,
    title: "Slow Motion",
    artist: "Luv Tonez",
    duration: "4:14",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Slow%20Motion-RnBSquare69.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Slow%20Motion-RnBSquare69.mp3",
    coverArt: "/rnb-square.jpg",
  },
  {
    id: 70,
    title: "Midnight Frequencies2",
    artist: "Luv Tonez",
    duration: "4:02",
    audioUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Midnight%20Frequencies2-RnBSquare70.mp3",
    downloadUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Midnight%20Frequencies2-RnBSquare70.mp3",
    coverArt: "/rnb-square.jpg",
  },
]

export function getAllRnBSquareTracks(): RnBSquareTrack[] {
  return rnbSquareTracks
}

export function getRnBSquareTrackById(id: number): RnBSquareTrack | undefined {
  return rnbSquareTracks.find((track) => track.id === id)
}

export const rnbSquareMetadata = {
  id: "rnb-square",
  title: "R&B SQUARE",
  artist: "Various AI Artists",
  genre: "R&B",
  releaseDate: "April 4, 2025",
  totalTracks: rnbSquareTracks.length,
  coverArt: "/rnb-square.jpg",
}
